### ISSUE TITLE
AdminsCanBypass

### ISSUE THREAD

**Issue by JustOneMoreBlock** [Plugins4Unturned/AdvancedChatControl#1]
AdminsCanBypass
- This needs to be permission based. I'm not going to provide full `Admin` access to Jr. Mods / Mods.

**Comment by Teyhota6** [comment]
Thx for the suggestion, ill add to my to-do list for the 1.2 update

**Comment by Teyhota6** [comment]
added permission **AdvancedChatControl.bypass** in experimental branch
